package constant

const (
	MsgErrorNotFound               = "data tidak ditemukan"
	MsgErrorConflict               = "data sudah ada"
	MsgErrorInternal               = "terjadi kesalahan"
	MsgErrorTimeout                = "request timeout"
	MsgInvalidRequest              = "request tidak valid"
	MsgSkuNotFound                 = "SKU tidak ditemukan"
	MsgStockNotEnough              = "Stok tidak cukup"
	MsgStockExist                  = "stok untuk SKU ini sudah ada"
	MsgStockNotFound               = "stock untuk SKU ini tidak ditemukan"
	MsgWarehouseNotFound           = "warehouse tidak ditemukan"
	MsgWarehouseStatusUpdated      = "status warehouse berhasil diubah"
	MsgStockCreated                = "stok berhasil dibuat"
	MsgStockUpdated                = "stok berhasil diubah"
	MsgStockTransferred            = "stok berhasil ditransfer"
	MsgAuthorizationHeaderNotFound = "authorization header tidak ditemukan"
	MsgInvalidFormatAuthorization  = "format authorization tidak valid"
	MsgInvalidSignature            = "signature tidak valid"
	MsgInvalidToken                = "token tidak valid"
	MsgExpiredToken                = "token sudah kadaluarsa"
	MsgAcknowledgeMessage          = "message acknowledged"
	MsgErrorAcknowledgeMessage     = "error acknowledge message"
	MsgMessageSent                 = "message sent"
)
